version: '3.1'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8234:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword